### PR TITLE
Add questions to custom form

### PR DESCRIPTION
**Pull request by Awesome-E**
**DO NOT MERGE OR APPROVE YET**

This is a draft PR so we can have changes on a separate branch, but still get a preview of it on render

### CODE REVIEW

**Comment by Awesome-E** [comment]
This PR should be ready. If either of you want to review it (Ethan K/Anthony), go for it.

We'll wait until API is fixed before merging

**Comment by Awesome-E** [comment]
Going to merge now just so we can get the thing up for MLH

**Review by anthonyj33 — COMMENTED** [review]
> This PR should be ready. If either of you want to review it (Ethan K/Anthony), go for it.

Since you already merged, I only took a pretty quick look over everything. LGTM tho 👍

**Comment by anthonyj33** [comment]
@Awesome-E 
Actually, now that I'm looking at it on the site, the school autocomplete doesn't seem to work for *any* CUSD schools I tried and it rejects schools that aren't on the list.. Where'd you get the dataset for the autocomplete?

**Pull request merged**
